### ISSUE TITLE
execute every 55 minutes?

### ISSUE THREAD

**Issue by jyjohnson** [aws-azure-login/aws-azure-login#19]
I think the script must use the AssumeRoleWithSAML STS API... as such, the token is limited to a max 1 hour duration. My folks are complaining about having to re-run the script every hour. So, would it be possible to add an optional setting that would keep the script running every 55 minutes (to regenerate the token before it expires)? 

Thanks.

**Comment by dtjohnson** [comment]
Yeah, it's a good idea. I had a branch open to work on this same idea, but it turns out to be a complicated issue. You need to detached from the shell. You need to deal with times when the machine is asleep/turned off or the network is unavailable. You also have to handle multiple profiles and potential race conditions if the script is run multiple times. I want to see it done, but it's a decent effort to do it right.

**Comment by TonyFNZ** [comment]
AWS temporary credentials now last up to 12 hours, so this shouldn't be as much of an issue
https://aws.amazon.com/blogs/security/enable-federated-api-access-to-your-aws-resources-for-up-to-12-hours-using-iam-roles/

**Comment by dtjohnson** [comment]
This is already done

**Comment by donotpush** [comment]
@dtjohnson how do we configure the app to use for instance 4h token?

I have added the following line to` ~/.aws/config` [the target profile]

`azure_default_duration_hours=4`

Unfortunately, the tokens are still getting 1-hour duration.

I have also modified:
- IAM role expiration time to 4 hours
- Office 365 application configuration - parameter session duration to 4 hours

**Comment by dtjohnson** [comment]
Did you install the latest version? You should be promoted for session
duration during configure and login.

On May 4, 2018 6:44 AM, "julianalves" <notifications@github.com> wrote:

@dtjohnson <https://github.com/dtjohnson> how do we configure the app to
use for instance 4h token?

I have added the following line to~/.aws/config [the target profile]

azure_default_duration_hours=4

Unfortunately, the tokens are still getting 1-hour duration.

I have also modified:

   - IAM role expiration time to 4 hours
   - Office 365 application configuration - parameter session duration to 4
   hours

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/dtjohnson/aws-azure-login/issues/19#issuecomment-386564761>,
or mute the thread

**Comment by dtjohnson** [comment]
Closing since we can have sessions up to 12 hours.

**Comment by donotpush** [comment]
@dtjohnson I have updated to the last version and it is working, thanks!
