### ISSUE TITLE
Error after OTP step  : ERROR: The process "12472" not found.

### ISSUE THREAD

**Issue by varun-viva** [aws-azure-login/aws-azure-login#92]
Getting the above error after the OTP step. Also the credentials generated last only for 15 min.

Can you please help on this

**Comment by varun-viva** [comment]
Also the STS token is created with the lowest timeout of 15 min it seems

**Comment by varun-viva** [comment]
While debugging we could see that the session timeout is passed before choosing the role to login and entering the session duration for the final time : 
`</Attribute><Attribute Name="https://aws.amazon.com/SAML/Attributes/SessionDuration"><AttributeValue>900</AttributeValue></Attribute></AttributeStatement>`

Even when we set the default duration as 5 hours , tool seems to be passing the minimum duration only. Could you please check and reply at the latest

CC : @dtjohnson @kennethaasan

**Comment by larsschumachenko** [comment]
As mentioned in the other issue, this doesn't sound like an issue with the aws-azure-login itself.
Based on the details provided here, I assume the problem lies within the initial setup of the SAML Identity Provider.

Have a look here:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html
and check the section for `SessionDuration`.

Basically: The lesser value of the 2 settings (The one in the SAML setup and the the one set for the IAM role itself) defines the maximum session duration.

**Comment by varun-viva** [comment]
This was an issue with Security token timeout set in Azure AD. When it was changed the issue was fixed. Thanks for looking in and supporting @larsschumachenko
